remeasure:
  fields:
    providers:
      required: false
      example: "mistral"
      selector:
        text:
          multiple: true
    liveness_only:
      required: false
      default: false
      selector:
        boolean:
